### ISSUE TITLE
Add search icon to the searchbar

### ISSUE THREAD

**Issue by Halim-Shams** [Halim-Shams/movie_app#1]
Add a search icon next to the placeholder, as long as the app is using Tailwindcss make sure you use Tailwind not pure CSS.

Options for choosing icon:
1. [react-icon](https://react-icons.github.io/react-icons)
2. [Heroicons](https://heroicons.com/)

![issue](https://user-images.githubusercontent.com/96909515/198938081-f6d98893-2824-415f-882a-7bfb232cfcb3.PNG)

**Comment by nishtha53** [comment]
can i work on this issue?

**Comment by Halim-Shams** [comment]
go ahead @nishtha53

**Comment by nishtha53** [comment]
sure.
Also, please can u add hacktoberfest label

**Comment by Halim-Shams** [comment]
@nishtha53  I added hacktoberfest label, now go ahead

**Comment by nishtha53** [comment]
okay thankyou i will update you soon.

**Comment by nishtha53** [comment]
@Halim-Shams please check PR

**Comment by Halim-Shams** [comment]
#2
